// <auto-generated />
using System;
using AIFunctionCallingRAG.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIFunctionCallingRAG.Data.Migrations
{
    [DbContext(typeof(EshopDbContext))]
    [Migration("20240520144021_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIFunctionCallingRAG.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AIFunctionCallingRAG.Data.Models.OrderProduct", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("AIFunctionCallingRAG.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3dc8f5f-679a-4c37-1496-9c948acce285"),
                            Color = "cyan",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Fantastic Soft Towels",
                            Price = 478.32m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("81c4566d-a2bc-600b-98b7-a829eb75dc45"),
                            Color = "magenta",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Licensed Fresh Bike",
                            Price = 932.70m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("6d4fd904-5dfc-5ba4-8bd3-b56e7cd5e57a"),
                            Color = "orange",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Awesome Soft Computer",
                            Price = 924.52m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("392810f7-5ea4-56f8-ca54-89c0a86d350e"),
                            Color = "green",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Incredible Wooden Hat",
                            Price = 729.47m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("4958705f-2c94-15d9-f022-36585cd42300"),
                            Color = "teal",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Generic Frozen Table",
                            Price = 646.32m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("f9740d3d-0f32-c582-4dc1-09c8c94b1563"),
                            Color = "indigo",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Generic Metal Bacon",
                            Price = 518.36m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("f4df3ad8-885d-4ad8-ec6c-5b1a3b1f32a6"),
                            Color = "black",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Handcrafted Rubber Tuna",
                            Price = 87.96m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("2fe7b459-fa53-5ada-75cb-f79cbf531b24"),
                            Color = "plum",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Intelligent Soft Chips",
                            Price = 288.67m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("49f644d9-2b3a-8742-7e85-2e8540765985"),
                            Color = "salmon",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Fantastic Cotton Soap",
                            Price = 473.80m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("49e95373-7520-3520-afeb-820deb5cb19f"),
                            Color = "lime",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Awesome Wooden Chips",
                            Price = 641.94m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("eee3aedb-0a27-884a-e295-c083f650e222"),
                            Color = "grey",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Generic Fresh Gloves",
                            Price = 2.33m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("729e296d-b2e1-cb0a-6de2-850e9b3c86f8"),
                            Color = "pink",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Gorgeous Soft Mouse",
                            Price = 65.52m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("114d4fba-1a31-12c6-331d-4576c5889869"),
                            Color = "lime",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Ergonomic Cotton Hat",
                            Price = 814.03m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("658be547-1924-1d37-f142-50e32394a0d8"),
                            Color = "cyan",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Handcrafted Soft Table",
                            Price = 137.71m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("fc936fc1-c88b-d7ad-384a-0d062ba6b4a1"),
                            Color = "olive",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Rustic Plastic Salad",
                            Price = 312.43m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("ff36d574-ac19-1dd0-50f1-1fc9f5911cab"),
                            Color = "teal",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Licensed Metal Chips",
                            Price = 364.67m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("04fc3275-56d6-02f0-924c-ca1e2755c893"),
                            Color = "magenta",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Incredible Frozen Bacon",
                            Price = 625.64m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("50dc10be-10ab-5cc9-0c5f-47c0cc1da8fa"),
                            Color = "tan",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Refined Steel Soap",
                            Price = 986.28m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("af8c55f5-b040-586b-7769-553df4f90545"),
                            Color = "lavender",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Handmade Frozen Computer",
                            Price = 44.66m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("6c8276fb-5c65-7e26-5f93-9de7fb1e6089"),
                            Color = "black",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Handmade Plastic Pizza",
                            Price = 375.54m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("1ac101b3-c4fd-6d8c-b316-c09039bd4406"),
                            Color = "silver",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Gorgeous Frozen Chips",
                            Price = 295.84m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("3f91270a-1d43-0fb8-3d84-97ce6aa34229"),
                            Color = "maroon",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Small Wooden Fish",
                            Price = 165.34m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("9a68cc26-7e0a-816c-345d-efb7f36b8549"),
                            Color = "gold",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Small Rubber Chips",
                            Price = 411.56m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("27b962d9-2231-6c84-41cf-986a73db82ae"),
                            Color = "red",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Handmade Soft Pants",
                            Price = 644.28m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("8933be4f-eed6-b7ca-8284-dd8f3751563b"),
                            Color = "yellow",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Generic Concrete Cheese",
                            Price = 291.06m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("4ccc6d12-b275-3f07-7c5d-776969fd99ad"),
                            Color = "teal",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Intelligent Concrete Pants",
                            Price = 557.53m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("953a5d4b-b1a5-ce81-03f5-bd211c09a254"),
                            Color = "magenta",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Handcrafted Steel Chair",
                            Price = 546.19m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("02c53ded-3671-43d1-1a7c-2081ef3b1c62"),
                            Color = "silver",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Tasty Plastic Mouse",
                            Price = 966.52m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("22dca47c-9b11-34a1-1a8a-754c58e0af0f"),
                            Color = "turquoise",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Handcrafted Rubber Pizza",
                            Price = 864.36m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("18e919b3-66b7-4ca2-7341-61485e9514bf"),
                            Color = "mint green",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Tasty Soft Car",
                            Price = 619.17m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("ebde81c4-42f7-07c2-3681-1c28092883ea"),
                            Color = "magenta",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Sleek Soft Table",
                            Price = 97.30m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("71837950-2a09-f55d-9139-2a2496d87aaa"),
                            Color = "magenta",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Refined Steel Fish",
                            Price = 47.02m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("8e25970a-8d79-76b7-e3cd-e98e7174d0b9"),
                            Color = "cyan",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Incredible Rubber Pants",
                            Price = 10.21m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("ce5411ec-5135-cbd1-d00f-0c78dae49be4"),
                            Color = "azure",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Practical Steel Computer",
                            Price = 936.63m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("f7393609-515d-b63b-7d2c-93387d25bf82"),
                            Color = "white",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Sleek Steel Bacon",
                            Price = 6.73m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("f441d4f6-b123-972c-ad3e-c74a98fc5973"),
                            Color = "violet",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Licensed Frozen Chicken",
                            Price = 490.58m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("56a8bf1e-349d-9454-caa4-3a43221c5c18"),
                            Color = "orange",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Unbranded Frozen Pizza",
                            Price = 100.42m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("9ecb8627-8487-d626-afae-2922357b5b8e"),
                            Color = "fuchsia",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Licensed Fresh Chair",
                            Price = 957.95m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("7c1d5736-3c54-61b7-b169-e580cfd295cd"),
                            Color = "ivory",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Licensed Metal Computer",
                            Price = 778.85m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("c3a99c26-8d32-b850-33c9-cd94466907d1"),
                            Color = "plum",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Handcrafted Concrete Computer",
                            Price = 354.69m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("8bccbb8b-5899-d3d9-243d-5ef7dfab7985"),
                            Color = "maroon",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Handmade Cotton Chair",
                            Price = 84.39m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("d309634f-9134-8147-41d6-a21d076501b7"),
                            Color = "azure",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Unbranded Rubber Mouse",
                            Price = 609.59m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("73202627-1778-9e07-4289-7d7d288f84a5"),
                            Color = "turquoise",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Practical Fresh Chair",
                            Price = 657.36m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("a9d31f71-5851-59c1-e766-f0e1ad131dce"),
                            Color = "mint green",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Licensed Steel Soap",
                            Price = 629.57m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("b4da27d8-cbb3-cb9b-52ea-98af53a56db5"),
                            Color = "black",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Ergonomic Frozen Soap",
                            Price = 12.41m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("0f2491d7-e351-dde8-f8e6-38fa8176a30e"),
                            Color = "orange",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Unbranded Wooden Fish",
                            Price = 83.75m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("84fc28ca-def1-f364-d0a1-7903238ebc49"),
                            Color = "orange",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Practical Fresh Hat",
                            Price = 489.77m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("72a23fec-4aa2-987b-b6c2-2d5ae6555ff6"),
                            Color = "green",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Unbranded Plastic Hat",
                            Price = 283.54m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("02d08080-35b2-75ea-9bae-7d10444e6cc2"),
                            Color = "cyan",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Small Concrete Salad",
                            Price = 998.15m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("7289f4d6-0b0d-b3d5-52e3-cb22f2d148c8"),
                            Color = "orchid",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Gorgeous Cotton Chips",
                            Price = 243.18m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("d192a71a-124a-4550-328a-4cfa0e29c2dc"),
                            Color = "indigo",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Incredible Frozen Tuna",
                            Price = 220.71m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("8c60f07a-f6a4-63f3-886c-ae6eca7a398a"),
                            Color = "grey",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Handcrafted Rubber Keyboard",
                            Price = 352.37m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("efa09f39-cbe3-3eb0-18a1-7b18e1e986ac"),
                            Color = "magenta",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handcrafted Steel Sausages",
                            Price = 253.15m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("3b2f61f7-2959-df8d-94d4-1826ed03070f"),
                            Color = "azure",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Sleek Fresh Pizza",
                            Price = 122.27m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("551ba158-594f-e170-49da-e3a98db39057"),
                            Color = "indigo",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Incredible Frozen Shoes",
                            Price = 951.53m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("3047a899-ec8f-c960-eea8-ffd79a3ed33d"),
                            Color = "teal",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Gorgeous Plastic Towels",
                            Price = 532.96m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("80075b79-0a18-670a-1d90-de81ad0829e1"),
                            Color = "turquoise",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Gorgeous Rubber Table",
                            Price = 430.10m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("4d4218f5-c43b-f852-768f-4dced4876c48"),
                            Color = "mint green",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Practical Wooden Computer",
                            Price = 644.85m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("415d3526-e6fc-133b-5aeb-7f1267d5bccf"),
                            Color = "violet",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Gorgeous Concrete Soap",
                            Price = 958.03m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("a1895a54-1251-acbf-9539-5c1b18de8255"),
                            Color = "orchid",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Generic Steel Cheese",
                            Price = 117.34m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("14027204-169d-54b0-cac7-fb08e77345ea"),
                            Color = "gold",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Small Wooden Computer",
                            Price = 989.69m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("7520f0a4-2c84-6b75-56ff-e5842e4ffd21"),
                            Color = "purple",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Ergonomic Cotton Shirt",
                            Price = 417.97m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("50cde19b-587a-6ba4-9cf9-b85d237ca12b"),
                            Color = "indigo",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Unbranded Wooden Fish",
                            Price = 78.48m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("79049b16-04a9-79f4-6588-198593b6dcfb"),
                            Color = "salmon",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Handcrafted Concrete Bike",
                            Price = 657.96m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("b9f4a4d9-3cbc-77f8-cd9a-f2b7b476dffa"),
                            Color = "mint green",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Awesome Cotton Tuna",
                            Price = 893.38m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("594a740d-f249-b874-639f-a92ad5b54b37"),
                            Color = "violet",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Fantastic Concrete Shoes",
                            Price = 352.79m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("b8338527-a12e-240b-1ccf-ace64471e3ae"),
                            Color = "cyan",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Licensed Rubber Pizza",
                            Price = 775.11m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("6f1a440a-e542-bdc5-0c6c-7523d3163946"),
                            Color = "lime",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Incredible Concrete Gloves",
                            Price = 78.74m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("be5ac606-f38a-1209-e71c-3929741332c9"),
                            Color = "indigo",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Rustic Cotton Cheese",
                            Price = 525.87m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("124c980f-36ca-7e9d-f1e1-7514a9e7263a"),
                            Color = "indigo",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Practical Fresh Keyboard",
                            Price = 991.83m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("8ee433c4-363c-8848-5436-774a263de13e"),
                            Color = "lime",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Small Granite Shirt",
                            Price = 14.68m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("1c18e188-9c48-4120-4775-ab87dee6a760"),
                            Color = "fuchsia",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Rustic Frozen Fish",
                            Price = 739.36m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("c4e8fc00-447e-5168-a5c5-345bac2419ff"),
                            Color = "grey",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Sleek Steel Bacon",
                            Price = 265.67m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("e9335802-9f56-deee-2157-45171f60d7a2"),
                            Color = "turquoise",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Unbranded Plastic Chair",
                            Price = 311.78m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("a92d3cfb-ed6c-01e8-c685-46e56c4a5a11"),
                            Color = "sky blue",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Refined Fresh Salad",
                            Price = 325.06m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("90149ffa-4ff7-74b2-f457-cd38ad28f582"),
                            Color = "maroon",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Refined Cotton Pants",
                            Price = 556.46m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("cea2586a-4f70-97db-8593-30330a575cf0"),
                            Color = "gold",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Gorgeous Soft Hat",
                            Price = 423.89m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("34bce8ad-daf5-e9af-7921-24aa38548141"),
                            Color = "salmon",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Small Concrete Table",
                            Price = 245.50m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("47942aeb-6aa3-8681-eccc-47f5e5b31ae5"),
                            Color = "magenta",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Gorgeous Plastic Computer",
                            Price = 539.35m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("d2309c24-39eb-56cd-6c30-f3d10a60920b"),
                            Color = "purple",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Practical Fresh Sausages",
                            Price = 714.58m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("330b8d9b-7202-c6fa-e305-7c70ab739796"),
                            Color = "orchid",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Rustic Wooden Sausages",
                            Price = 444.84m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("ca2b850f-bd2b-ad75-cf33-3c9444e006cb"),
                            Color = "red",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Intelligent Soft Chicken",
                            Price = 924.42m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("62e798e6-184f-1667-9ba9-abfbaed6a7cf"),
                            Color = "white",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Ergonomic Frozen Keyboard",
                            Price = 205.19m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("5446b652-6992-e25a-1682-954532435b26"),
                            Color = "lavender",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Small Frozen Computer",
                            Price = 839.59m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("a13cf457-a160-e073-b276-ba94ab08c4d5"),
                            Color = "turquoise",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Awesome Concrete Cheese",
                            Price = 593.44m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("47ad8c75-45c3-ce20-f2b9-d1ee5f55c8fa"),
                            Color = "mint green",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Licensed Steel Bacon",
                            Price = 37.79m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("92d01daf-6070-0425-6c3f-62c615b25ab0"),
                            Color = "orange",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Refined Cotton Car",
                            Price = 151.36m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("46e47f64-f185-36d6-c3fd-ddfd29f2b2b0"),
                            Color = "gold",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Sleek Plastic Shirt",
                            Price = 777.71m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("f1e747b3-5006-af26-d4d5-036b128c1aa0"),
                            Color = "turquoise",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Incredible Steel Towels",
                            Price = 12.90m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("e1e8bd30-fb3a-7425-6a67-f130ff9dffcf"),
                            Color = "blue",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Unbranded Wooden Sausages",
                            Price = 484.21m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("2b5323a0-d0a2-5da6-c57b-92b6341e6feb"),
                            Color = "blue",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Handmade Granite Salad",
                            Price = 488.33m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("c512021b-0223-2f7a-8c09-3648bde6cf82"),
                            Color = "lavender",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Incredible Frozen Shoes",
                            Price = 906.28m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("b175b1cb-5a9a-8dc7-837e-c83828900a82"),
                            Color = "green",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handcrafted Wooden Chicken",
                            Price = 606.15m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("2ce404b1-d4bb-f5f9-a5ae-1b4613ae51e0"),
                            Color = "cyan",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Generic Metal Chicken",
                            Price = 210.10m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("419af2a6-e0ae-6769-39ce-dcc4acb52e0c"),
                            Color = "lime",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Rustic Soft Shoes",
                            Price = 936.27m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("6909d4f7-4177-4a30-0bbb-563d3921924a"),
                            Color = "mint green",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Gorgeous Frozen Chair",
                            Price = 685.69m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("b8a62ba4-28c3-d340-2399-a8a36da576f2"),
                            Color = "mint green",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Awesome Metal Table",
                            Price = 315.41m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("3f26ebf4-e673-2a43-d1bf-ea653ed0886c"),
                            Color = "white",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Refined Granite Bacon",
                            Price = 176.60m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("499ea524-d820-66f4-e04e-b2b2cd9de9cd"),
                            Color = "silver",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Small Fresh Gloves",
                            Price = 738.63m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("9d9d2138-0561-2320-d462-6c0199d59c22"),
                            Color = "tan",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Handcrafted Concrete Chicken",
                            Price = 749.94m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("fd39cebb-52fb-bb34-9ba1-656528833b92"),
                            Color = "mint green",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Awesome Metal Computer",
                            Price = 738.89m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("bd50f84f-f81c-7989-28ac-04e1ce280824"),
                            Color = "lime",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Small Concrete Salad",
                            Price = 490.44m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("4a179f74-49f8-adec-cd5b-31e905aa9518"),
                            Color = "olive",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Rustic Cotton Pants",
                            Price = 778.43m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("9b596a6c-3e5a-8ea8-3d1b-88dc1d05ad91"),
                            Color = "orange",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Intelligent Fresh Hat",
                            Price = 948.33m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("873b7a02-c0e4-f636-b650-fdaae09ead92"),
                            Color = "plum",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Generic Cotton Pants",
                            Price = 62.53m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("7f141377-01f8-edba-1bd0-2b56211eb6c4"),
                            Color = "turquoise",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Generic Cotton Shirt",
                            Price = 790.51m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("a982f2cd-118f-a8b8-7185-acc374cf413e"),
                            Color = "white",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Generic Metal Sausages",
                            Price = 574.78m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("60b9738b-edff-aaa8-4158-b8478c75572b"),
                            Color = "salmon",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Rustic Metal Mouse",
                            Price = 835.13m,
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("c78cf441-d630-3e29-8018-aaf736d6b1b8"),
                            Color = "orchid",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Tasty Wooden Hat",
                            Price = 256.53m,
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("d09dc9b5-7e87-fab2-7716-17776b732578"),
                            Color = "fuchsia",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handcrafted Frozen Salad",
                            Price = 204.61m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("aa295521-f16d-0bf5-f085-6cd6fe9206a2"),
                            Color = "teal",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Handmade Metal Table",
                            Price = 735.98m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("50944446-5207-8451-59d2-4b7c7b5dd445"),
                            Color = "tan",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Gorgeous Plastic Salad",
                            Price = 953.35m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("74cde527-6a5a-af11-9d02-f6e365d8a0ee"),
                            Color = "mint green",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Generic Concrete Mouse",
                            Price = 565.89m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("88ea458b-b014-f7d5-6c47-a76d6a39ddf6"),
                            Color = "mint green",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Tasty Plastic Pizza",
                            Price = 377.77m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("93696d6e-8753-ebf0-9874-d0422f70e2fd"),
                            Color = "violet",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Small Metal Table",
                            Price = 120.00m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("a9dab435-cbe7-05e0-9b06-cc7b1aab1c82"),
                            Color = "tan",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Fantastic Concrete Salad",
                            Price = 223.85m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("4a3886ae-e523-fb6f-dcb1-0233df78dd09"),
                            Color = "olive",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Fantastic Cotton Chips",
                            Price = 105.47m,
                            Size = "S"
                        },
                        new
                        {
                            Id = new Guid("45e351c7-0d9a-ae41-729a-bd2b23ae80bc"),
                            Color = "orange",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Handcrafted Rubber Towels",
                            Price = 437.55m,
                            Size = "XL"
                        },
                        new
                        {
                            Id = new Guid("7292093c-563a-6589-ba4b-9270f840a0d5"),
                            Color = "maroon",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Ergonomic Plastic Chicken",
                            Price = 202.17m,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = new Guid("fba05aba-0950-7331-29ae-daa63c079a07"),
                            Color = "orange",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Gorgeous Frozen Towels",
                            Price = 905.11m,
                            Size = "XXL"
                        });
                });

            modelBuilder.Entity("AIFunctionCallingRAG.Data.Models.OrderProduct", b =>
                {
                    b.HasOne("AIFunctionCallingRAG.Data.Models.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIFunctionCallingRAG.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AIFunctionCallingRAG.Data.Models.Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
